-- Migration for 4vCHEF Schema

CREATE TABLE TIPO_RECETA (
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    PRIMARY KEY(id)
) ENGINE = InnoDB;

CREATE TABLE TIPO_NUTRIENTE (
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    unit VARCHAR(50) NOT NULL,
    PRIMARY KEY(id)
) ENGINE = InnoDB;

CREATE TABLE RECETA (
    id INT AUTO_INCREMENT NOT NULL,
    type_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    diners INT NOT NULL,
    description TEXT,
    deleted_at DATETIME DEFAULT NULL,
    INDEX IDX_RECIPE_TYPE (type_id),
    PRIMARY KEY(id),
    CONSTRAINT FK_RECIPE_TYPE FOREIGN KEY (type_id) REFERENCES TIPO_RECETA (id)
) ENGINE = InnoDB;

CREATE TABLE INGREDIENTE (
    id INT AUTO_INCREMENT NOT NULL,
    recipe_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    unit VARCHAR(50) NOT NULL,
    INDEX IDX_INGREDIENT_RECIPE (recipe_id),
    PRIMARY KEY(id),
    CONSTRAINT FK_INGREDIENT_RECIPE FOREIGN KEY (recipe_id) REFERENCES RECETA (id) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE PASO (
    id INT AUTO_INCREMENT NOT NULL,
    recipe_id INT NOT NULL,
    `order` INT NOT NULL,
    description TEXT NOT NULL,
    INDEX IDX_STEP_RECIPE (recipe_id),
    PRIMARY KEY(id),
    CONSTRAINT FK_STEP_RECIPE FOREIGN KEY (recipe_id) REFERENCES RECETA (id) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE NUTRIENTE_RECETA (
    id INT AUTO_INCREMENT NOT NULL,
    recipe_id INT NOT NULL,
    nutrient_type_id INT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    INDEX IDX_RN_RECIPE (recipe_id),
    INDEX IDX_RN_NUTRIENT (nutrient_type_id),
    PRIMARY KEY(id),
    CONSTRAINT FK_RN_RECIPE FOREIGN KEY (recipe_id) REFERENCES RECETA (id) ON DELETE CASCADE,
    CONSTRAINT FK_RN_NUTRIENT FOREIGN KEY (nutrient_type_id) REFERENCES TIPO_NUTRIENTE (id)
) ENGINE = InnoDB;

CREATE TABLE VALORACION (
    id INT AUTO_INCREMENT NOT NULL,
    recipe_id INT NOT NULL,
    value INT NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    INDEX IDX_RATING_RECIPE (recipe_id),
    UNIQUE INDEX UNIQ_RATING_RECIPE_IP (recipe_id, ip_address),
    PRIMARY KEY(id),
    CONSTRAINT FK_RATING_RECIPE FOREIGN KEY (recipe_id) REFERENCES RECETA (id)
) ENGINE = InnoDB;
